controller_manager_ns: controller_manager 
controller_list:  
  - name: schunk/schunk_arm_controller    
    action_ns: follow_joint_trajectory     
    type: FollowJointTrajectory    
    default: true    
    joints:      
      - joint1     
      - joint2      
      - joint3       
      - joint4      
      - joint5       
         
      
  - name: schunk/end_effector_controller
    action_ns: follow_joint_trajectory    
    type: FollowJointTrajectory    
    default: true    
    joints:       
      - joint6     
     